language: r
r:
- release
- devel
sudo: false
cache: packages
os:
- linux
r_github_packages:
- jimhester/covr
- yihui/knitr
after_success:
- if [[ "$TRAVIS_R_VERSION" != "devel" && ("$TRAVIS_OS_NAME" == "linux") ]]; then Rscript -e 'covr::codecov(type = "example",
  quiet = FALSE)'; fi
